name: Check code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Poetry
      uses: snok/install-poetry@b67da837e42fb77252a06a3eb84cf0ccaad73aa9
      with:
        version: 1.1.5
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached dependencies
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Check formatting with Black
      run: poetry run black --check .

    - name: Type check with Mypy
      run: poetry run mypy
